## YAML Template.
---

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SHORTURL
  Sample SAM Template for URL-Shortener-App
  
##Globals:
##  Function:
##    Timeout: 30
##    MemorySize: 2048

Resources:
  ShortUrl:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.mycompany.urlshortener.lambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 2048
      Timeout: 30
##      SnapStart:
##        ApplyOn: "PublishedVersions"
##      AutoPublishAlias: "prod"
##      Environment:
##        Variables:
##          MAIN_CLASS: com.mycompany.urlshortener.UrlShortener
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  MyApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
